title: String Theory
description: Thoughts on tech from someone who likes yarn.

url: http://natdudley.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: natdudley
   twitter: natdudley
   email: natalie.dudley@gmail.com
